### ISSUE TITLE
ETS更新了，全局界面变成蓝色系了，pic里的图片需要更换

### ISSUE THREAD

**Issue by GaoYuan522** [deAlue/AutoETS#1]

**Comment by deAlue** [comment]
😭随便做的项目竟然有了issue。ets我不知道现在我还能不能登，有空的时候我看看能不能更新一下🙏

**Comment by GaoYuan522** [comment]
> 😭随便做的项目竟然有了issue。ets我不知道现在我还能不能登，有空的时候我看看能不能更新一下🙏

可以结合隔壁的自动获取ETS答案应用开发，这样就能搞定模考模式，模考模式太烦人了！

**Comment by ycccccccy** [comment]
我只适配了深圳题库，毕竟我就在深圳，所以题目不一样自然也就不好搞，想搞的话邮箱发给我微信吧
