### ISSUE TITLE
定位ETS的音频存储位置

### ISSUE THREAD

**Issue by Hwenray** [deAlue/AutoETS#2]
事实上不用录音，在”%AppData%/74656D705F74656D705F74656D705F74002/xxxxx“
下就会有音频文件 但是74656D705F74656D705F74656D705F74002可能每台设备不一样，要手动寻找到才行（通过查找作业/课文的id）
![158986f61891eb26ff2d24c7c823f4cb](https://github.com/user-attachments/assets/56e16e0e-f0f0-4a3b-a8ba-cd8cf2213637)
源文件夹均为带密码压缩包，appdata中全部解压出来了，即可获取到录音文件
![92a3e31a4f37617b82ab32825b73b924](https://github.com/user-attachments/assets/32a7d76d-6be2-4d97-8373-1e8ce93639b6)
yi因此可以先把”%AppData%/74656D705F74656D705F74656D705F74002/“下的数字命名的文件夹删除后通过按顺序进入并下载作业即可实现自动判断语音文件的位置并自动播放了，且目前实测教师端无法收听学生音频（仍存疑？），可放心采用本项目。

**Comment by deAlue** [comment]
好想法，之前也有想过抓包获取音频，但当时时间仓促就用了这个笨方法。但是我的ets账号已经过期了，也许没办法继续开发了😭

**Comment by deAlue** [comment]
我这边搞到了ets使用，发现同样也是74656D705F74656D705F74656D705F74002，所以这个思路是可行的，非常感谢

**Comment by Hwenray** [comment]
&有一些东西说一下
ETS的数据库时裸奔的，直接读/写都没问题
利用这个可以实现过期续签（理论上）
现在我的ets e卡已经过了😓

**Comment by deAlue** [comment]
这不好罢，这个有被ban的风险罢

**Comment by Hwenray** [comment]
![图片](https://github.com/user-attachments/assets/292aa84b-1be6-43a4-962c-8d1fd89e8aa0)
![图片](https://github.com/user-attachments/assets/f0b2a448-7b27-4575-8e63-c44c27fccb24)

**Comment by Hwenray** [comment]
&代码属于是应该优化一下了~~~顺便把使用引导也优化一下（（（到时候可以封装成cil命令行应用

**Comment by deAlue** [comment]
小孩子不懂事搓着玩的，本人技术力不高，如果你能做出来可以push出来

**Comment by Hwenray** [comment]
本来想搞的，但是发现E卡过期就不用完成任务了（找到借口了（bushi
所以就放弃了（下次再说罢

**Comment by tym2008** [comment]
ETS V5.7.2更新，路径变更为%AppData%\ETS 好像格式没有更新
